### ISSUE TITLE
Usuário do lider do grupo

### ISSUE THREAD

**Issue by nukdown** [fga-verival/2019-2Grupo1#1]
Comentem nessa issue o usuário github do lider do grupo 1, que será responsável por dar privilegio para os demais membros neste repositório.

**Comment by Miguel-Alves** [comment]
Miguel-Alves

**Comment by gustavoduartemoreira** [comment]
Opa! gustavoduartemoreira

**Comment by nukdown** [comment]
@gustavoduartemoreira  só add sua galera!
